### ISSUE TITLE
Errors for Deployed Pipelines

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/public-roadmap#92]
We currently do not show errors for deployed pipelines. That's a problem!

```[tasklist]
### Definition of Done
- [x] Design where to show errors for deployed pipelines and how to make users aware of them.
- [x] Deliver errors to the app
- [x] Show errors for deployed pipelines in the app.
```
```[tasklist]
### Tasks
- [ ] https://github.com/tenzir/issues/issues/867
```
