### ISSUE TITLE
Distinguish Created vs. Disconnected Nodes

### ISSUE THREAD

**Issue by lava** [tenzir/public-roadmap#96]
From an onboarding perspective, it's important to understand the difference between creating a node in the configurator and achieving the next step, i.e., connecting it. This roadmap item is about making this possible to differentiate. 

```[tasklist]
### Tasks
- [ ] https://github.com/tenzir/issues/issues/573
- [ ] https://github.com/tenzir/issues/issues/820
- [ ] https://github.com/tenzir/issues/issues/840
```
