### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#97]
Feedback from an alpha tester:

> It would be nice on ANY of these middle screen windows to be able to press up arrow and/or down arrow to navigate to next record in list (or previous). Right now I must mouse-over and click, which slows me down.

```[tasklist]
### Tasks
- [ ] Lay out all user actions that should have a keyboard shortcut
- [ ] Implement them in the app
- [ ] Create a help screen that lists all keyboard shortcut (e.g., a modal when pressing `?`)
```

**Comment by dominiklohmann** [comment]
There's no acute need for this right now.
